### ISSUE TITLE
Add support for ruff and the other modern tooling that is now in HDMF

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf-zarr#91]
To keep in line with HDMF:
The Python Packaging Authority is gradually phasing out `setup.py` in favor of `pyproject.toml`. We make the change here. 

This involves removing `versioneer` as a dependency due to challenges to get it to play nicely with `pyproject.toml`. Using `setuptools_scm` for setting the package version appears to be an adequate replacement. 

~~We will also now be using the popular `black` and `ruff` tools to impose a strict, mostly uncompromising style on the code base. `ruff` replaces `flake8` and `isort` and performs additional checks. Running these tools on the code base involves changing basically every python file...~~

We will now use `ruff` to replace `flake8`. It is significantly faster, sorts imports, and performs additional checks.

Finally, to help automate the usage of ~~`black`~~, `ruff`, `codespell`, I recommend that developers install and use `pre-commit`, which runs these tools as well as several other helpful utility functions, to clean up the code and identify issues prior to every commit.

**Comment by rly** [comment]
We will need to replace `versioneer.py` soon. When trying to install hdmf-zarr with Python 3.12, I get this error on the bundled versioneer and the `configparser` that comes with Python 3.12.

```
Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1zfqiwk7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 468, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1zfqiwk7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1zfqiwk7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1zfqiwk7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1zfqiwk7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
        File "/home/runner/work/hdmf/hdmf/hdmf-zarr/versioneer.py", line 1540, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/home/runner/work/hdmf/hdmf/hdmf-zarr/versioneer.py", line 1472, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/hdmf/hdmf/hdmf-zarr/versioneer.py", line 343, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
``` 

This is mostly just a tedious migration based on what we are now using in HDMF. I'll try to tackle the upgrade in the next two weeks.

**Comment by rly** [comment]
This is done
